### ISSUE TITLE
JSONException: no value for coord

### ISSUE THREAD

**Issue by ThePsychicVictini** [survivingwithandroid/WeatherLib#30]
Checking the API, There is a "coord" value, but it just throws error, and doesn't do anything. Don't know what's happening here.

08-11 11:52:00.793  17126-17142/com.azdevelopergamer.weatherwatchface D/LocationCheck﹕ Lat, Long: 44.03556347  -103.26744921
08-11 11:52:00.943  17126-17142/com.azdevelopergamer.weatherwatchface E/DataScheduler﹕ isDataSchedulerEnabled():false
08-11 11:52:01.163  17126-17142/com.azdevelopergamer.weatherwatchface W/System.err﹕ org.json.JSONException: No value for coord
08-11 11:52:01.163  17126-17142/com.azdevelopergamer.weatherwatchface W/System.err﹕ at org.json.JSONObject.get(JSONObject.java:355)
08-11 11:52:01.163  17126-17142/com.azdevelopergamer.weatherwatchface W/System.err﹕ at org.json.JSONObject.getJSONObject(JSONObject.java:574)
08-11 11:52:01.163  17126-17142/com.azdevelopergamer.weatherwatchface W/System.err﹕ at com.survivingwithandroid.weather.lib.provider.openweathermap.OpenweathermapProvider.getObject(OpenweathermapProvider.java:505)
08-11 11:52:01.163  17126-17142/com.azdevelopergamer.weatherwatchface W/System.err﹕ at com.survivingwithandroid.weather.lib.provider.openweathermap.OpenweathermapProvider.getCurrentCondition(OpenweathermapProvider.java:91)
08-11 11:52:01.163  17126-17142/com.azdevelopergamer.weatherwatchface W/System.err﹕ at com.survivingwithandroid.weather.lib.StandardHttpClient.getCurrentCondition(StandardHttpClient.java:454)
08-11 11:52:01.163  17126-17142/com.azdevelopergamer.weatherwatchface W/System.err﹕ at com.azdevelopergamer.weatherwatchface.WeatherService$GetWeatherTask.doInBackground(WeatherService.java:92)
08-11 11:52:01.163  17126-17142/com.azdevelopergamer.weatherwatchface W/System.err﹕ at android.os.AsyncTask$2.call(AsyncTask.java:288)
08-11 11:52:01.163  17126-17142/com.azdevelopergamer.weatherwatchface W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:237)
08-11 11:52:01.163  17126-17142/com.azdevelopergamer.weatherwatchface W/System.err﹕ at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
08-11 11:52:01.163  17126-17142/com.azdevelopergamer.weatherwatchface W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
08-11 11:52:01.163  17126-17142/com.azdevelopergamer.weatherwatchface W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
08-11 11:52:01.163  17126-17142/com.azdevelopergamer.weatherwatchface W/System.err﹕ at java.lang.Thread.run(Thread.java:841)
08-11 11:52:01.163  17126-17142/com.azdevelopergamer.weatherwatchface D/WL﹕ Weather Error - parsing data
08-11 11:52:01.173  17126-17142/com.azdevelopergamer.weatherwatchface W/System.err﹕ com.survivingwithandroid.weather.lib.exception.WeatherLibException: org.json.JSONException: No value for coord
08-11 11:52:01.173  17126-17142/com.azdevelopergamer.weatherwatchface W/System.err﹕ at com.survivingwithandroid.weather.lib.provider.openweathermap.OpenweathermapProvider.getCurrentCondition(OpenweathermapProvider.java:175)
08-11 11:52:01.173  17126-17142/com.azdevelopergamer.weatherwatchface W/System.err﹕ at com.survivingwithandroid.weather.lib.StandardHttpClient.getCurrentCondition(StandardHttpClient.java:454)
08-11 11:52:01.173  17126-17142/com.azdevelopergamer.weatherwatchface W/System.err﹕ at com.azdevelopergamer.weatherwatchface.WeatherService$GetWeatherTask.doInBackground(WeatherService.java:92)
08-11 11:52:01.173  17126-17142/com.azdevelopergamer.weatherwatchface W/System.err﹕ at android.os.AsyncTask$2.call(AsyncTask.java:288)
08-11 11:52:01.173  17126-17142/com.azdevelopergamer.weatherwatchface W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:237)
08-11 11:52:01.173  17126-17142/com.azdevelopergamer.weatherwatchface W/System.err﹕ at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
08-11 11:52:01.173  17126-17142/com.azdevelopergamer.weatherwatchface W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
08-11 11:52:01.173  17126-17142/com.azdevelopergamer.weatherwatchface W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
08-11 11:52:01.173  17126-17142/com.azdevelopergamer.weatherwatchface W/System.err﹕ at java.lang.Thread.run(Thread.java:841)
08-11 11:52:01.173  17126-17142/com.azdevelopergamer.weatherwatchface W/System.err﹕ Caused by: org.json.JSONException: No value for coord
08-11 11:52:01.173  17126-17142/com.azdevelopergamer.weatherwatchface W/System.err﹕ at org.json.JSONObject.get(JSONObject.java:355)
08-11 11:52:01.173  17126-17142/com.azdevelopergamer.weatherwatchface W/System.err﹕ at org.json.JSONObject.getJSONObject(JSONObject.java:574)
08-11 11:52:01.173  17126-17142/com.azdevelopergamer.weatherwatchface W/System.err﹕ at com.survivingwithandroid.weather.lib.provider.openweathermap.OpenweathermapProvider.getObject(OpenweathermapProvider.java:505)
08-11 11:52:01.173  17126-17142/com.azdevelopergamer.weatherwatchface W/System.err﹕ at com.survivingwithandroid.weather.lib.provider.openweathermap.OpenweathermapProvider.getCurrentCondition(OpenweathermapProvider.java:91)
08-11 11:52:01.173  17126-17142/com.azdevelopergamer.weatherwatchface W/System.err﹕ ... 8 more

**Comment by ThePsychicVictini** [comment]
Never mind, long lat, not lat long.(US I think is always lat long).
