### ISSUE TITLE
Json Problm

### ISSUE THREAD

**Issue by omidjoon** [survivingwithandroid/WeatherLib#38]
10-27 23:36:52.331  10578-10578/ir.developer.omiderfanmanesh.project1 D/Swa﹕ City Id [/q/zmw:00000.1.42114]
10-27 23:36:53.512  10578-10822/ir.developer.omiderfanmanesh.project1 W/System.err﹕ org.json.JSONException: No value for forecast
10-27 23:36:53.512  10578-10822/ir.developer.omiderfanmanesh.project1 W/System.err﹕ at org.json.JSONObject.get(JSONObject.java:389)
10-27 23:36:53.512  10578-10822/ir.developer.omiderfanmanesh.project1 W/System.err﹕ at org.json.JSONObject.getJSONObject(JSONObject.java:609)
10-27 23:36:53.512  10578-10822/ir.developer.omiderfanmanesh.project1 W/System.err﹕ at com.survivingwithandroid.weather.lib.provider.wunderground.WeatherUndergroundProvider.getObject(WeatherUndergroundProvider.java:512)
10-27 23:36:53.512  10578-10822/ir.developer.omiderfanmanesh.project1 W/System.err﹕ at com.survivingwithandroid.weather.lib.provider.wunderground.WeatherUndergroundProvider.parseForecast(WeatherUndergroundProvider.java:204)
10-27 23:36:53.513  10578-10822/ir.developer.omiderfanmanesh.project1 W/System.err﹕ at com.survivingwithandroid.weather.lib.provider.wunderground.WeatherUndergroundProvider.getForecastWeather(WeatherUndergroundProvider.java:194)
10-27 23:36:53.513  10578-10822/ir.developer.omiderfanmanesh.project1 W/System.err﹕ at com.survivingwithandroid.weather.lib.client.okhttp.WeatherDefaultClient$5.onResponse(WeatherDefaultClient.java:426)
10-27 23:36:53.513  10578-10822/ir.developer.omiderfanmanesh.project1 W/System.err﹕ at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:162)
10-27 23:36:53.513  10578-10822/ir.developer.omiderfanmanesh.project1 W/System.err﹕ at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
10-27 23:36:53.513  10578-10822/ir.developer.omiderfanmanesh.project1 W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
10-27 23:36:53.513  10578-10822/ir.developer.omiderfanmanesh.project1 W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
10-27 23:36:53.513  10578-10822/ir.developer.omiderfanmanesh.project1 W/System.err﹕ at java.lang.Thread.run(Thread.java:818)

**Comment by omidjoon** [comment]
why?
