### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by athkalia** [survivingwithandroid/WeatherLib#44]
Hello, I am getting a NullPointerException from your library. Unfortunately the code is obfuscated so I can't trace it down 100%

```
java.lang.NullPointerException: Attempt to invoke virtual method 'double org.json.JSONObject.optDouble(java.lang.String)' on a null object reference
    at com.survivingwithandroid.weather.lib.provider.openweathermap.OpenweathermapProvider.getCurrentCondition(SourceFile:1516)
    at bno.onResponse(SourceFile:380)
    at bkr.execute(SourceFile:162)
    at com.squareup.okhttp.internal.NamedRunnable.run(SourceFile:33)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:818)
```

Edit:

We are getting the exception because the response is a weird openweathermap response, error 401 that can't be parsed by your library. The easiest way to fix this is to catch NullpointExceptions and return an empty weather object.

The json we receive is: 
{"cod":401, "message": "Invalid API key. Please see http://openweathermap.org/faq#error401 for more info."}

**Comment by athkalia** [comment]
Note: 

In their json respond api here
http://openweathermap.org/current#current_JSON
there's no "gust" field at all ! Maybe you should just remove that ?

Cheers

**Comment by athkalia** [comment]
This is still an issue for us. Any update on whether it's getting fixed?  We are about to wrap your library calls into a try/catch statement to stop our app from crashing. If the API of weather providers changes all the time, I suggest you do the same and propagate that error via 
```
onWeatherError()
```
The same way as you currently only do for JSONExceptions.

**Comment by Seichis** [comment]
@athkalia So this is still an issue. How did you deal with it?

**Comment by athkalia** [comment]
I made a fork that catches all exceptions and forwards them accordingly in the already existing onError listeners. It's this one.
https://github.com/athkalia/WeatherLib . This is the only change:
https://github.com/athkalia/WeatherLib/commit/44a43e0b5c339e820521bdf538883733f38906fe

**Comment by tsakmalis** [comment]
The same problem happens to me! How can I handle this?
